### ISSUE TITLE
Update the project

### ISSUE THREAD

**Issue by WorldWonderful10** [Neerajsh8851/game_recorder#1]
I liked of project and suggest a update to work fine on more recents android versions (working only until android **8.1**). Are they:

1 - [Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE TYPE_MEDIA_PROJECTION in Android Pie and Q](https://stackoverflow.com/questions/61276730/media-projections-require-a-foreground-service-of-type-serviceinfo-foreground-se)

2 - [java.lang.IllegalStateException: failed to get surface](https://stackoverflow.com/questions/35711723/java-lang-illegalstateexception-failed-to-get-surface)

**Comment by neerajshdev** [comment]
I will update the project soon 😊.

**Comment by omardri** [comment]
I'm curious what causing that issue

**Comment by neerajshdev** [comment]
I recently updated the project. 

    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>

This two permission was required.
